### PR TITLE
Add manual pages.

### PR DESCRIPTION
**Pull request by porridge**
Also attempt to install them in setup.py and mention them in the README.

No manual page for updateprices since it seems to no longer work.

### CODE REVIEW

**Comment by Rudd-O** [comment]
This broke build from RPM.

```
Bytecompiling .py files below /home/user/Projects/ledgerhelpers/build/bdist.linux-x86_64/rpm/BUILDROOT/ledgerhelpers-0.3.8-1.fc36.x86_64/usr/lib/python3.10 using python3.10
+ /usr/lib/rpm/redhat/brp-python-hardlink
Processing files: ledgerhelpers-0.3.8-1.fc36.noarch
error: File not found: /home/user/Projects/ledgerhelpers/build/bdist.linux-x86_64/rpm/BUILDROOT/ledgerhelpers-0.3.8-1.fc36.x86_64/usr/share/man/man1/sellstock-cli.1
error: File not found: /home/user/Projects/ledgerhelpers/build/bdist.linux-x86_64/rpm/BUILDROOT/ledgerhelpers-0.3.8-1.fc36.x86_64/usr/share/man/man1/addtrans.1
error: File not found: /home/user/Projects/ledgerhelpers/build/bdist.linux-x86_64/rpm/BUILDROOT/ledgerhelpers-0.3.8-1.fc36.x86_64/usr/share/man/man1/withdraw-cli.1
error: File not found: /home/user/Projects/ledgerhelpers/build/bdist.linux-x86_64/rpm/BUILDROOT/ledgerhelpers-0.3.8-1.fc36.x86_64/usr/share/man/man1/cleartrans-cli.1
error: File not found: /home/user/Projects/ledgerhelpers/build/bdist.linux-x86_64/rpm/BUILDROOT/ledgerhelpers-0.3.8-1.fc36.x86_64/usr/share/man/man1/sorttrans-cli.1
Executing(%doc): /bin/sh -e /var/tmp/rpm-tmp.c0xpCC
+ umask 022
+ cd /home/user/Projects/ledgerhelpers/build/bdist.linux-x86_64/rpm/BUILD
+ cd ledgerhelpers-0.3.8
+ DOCDIR=/home/user/Projects/ledgerhelpers/build/bdist.linux-x86_64/rpm/BUILDROOT/ledgerhelpers-0.3.8-1.fc36.x86_64/usr/share/doc/ledgerhelpers
+ export LC_ALL=C
+ LC_ALL=C
+ export DOCDIR
+ /usr/bin/mkdir -p /home/user/Projects/ledgerhelpers/build/bdist.linux-x86_64/rpm/BUILDROOT/ledgerhelpers-0.3.8-1.fc36.x86_64/usr/share/doc/ledgerhelpers
+ cp -pr README.md /home/user/Projects/ledgerhelpers/build/bdist.linux-x86_64/rpm/BUILDROOT/ledgerhelpers-0.3.8-1.fc36.x86_64/usr/share/doc/ledgerhelpers
+ RPM_EC=0
++ jobs -p
+ exit 0

RPM build errors:
    File not found: /home/user/Projects/ledgerhelpers/build/bdist.linux-x86_64/rpm/BUILDROOT/ledgerhelpers-0.3.8-1.fc36.x86_64/usr/share/man/man1/sellstock-cli.1
    File not found: /home/user/Projects/ledgerhelpers/build/bdist.linux-x86_64/rpm/BUILDROOT/ledgerhelpers-0.3.8-1.fc36.x86_64/usr/share/man/man1/addtrans.1
    File not found: /home/user/Projects/ledgerhelpers/build/bdist.linux-x86_64/rpm/BUILDROOT/ledgerhelpers-0.3.8-1.fc36.x86_64/usr/share/man/man1/withdraw-cli.1
    File not found: /home/user/Projects/ledgerhelpers/build/bdist.linux-x86_64/rpm/BUILDROOT/ledgerhelpers-0.3.8-1.fc36.x86_64/usr/share/man/man1/cleartrans-cli.1
    File not found: /home/user/Projects/ledgerhelpers/build/bdist.linux-x86_64/rpm/BUILDROOT/ledgerhelpers-0.3.8-1.fc36.x86_64/usr/share/man/man1/sorttrans-cli.1
```

Let me find a solution for this.

**Comment by porridge** [comment]
Looks like [CI is now broken](https://github.com/Rudd-O/ledgerhelpers/actions/runs/3528515253/jobs/5918701574) too :-/

**Comment by Rudd-O** [comment]
Yes that makes sense.

**Comment by Rudd-O** [comment]
I'm fixing CI, please stand by.

**Comment by Rudd-O** [comment]
I think I fixed CI.  Check the actions tab please.  Thanks for the heads up.

**Pull request merged**
